
spring:
    datasource :
        url: jdbc:mysql://localhost:3306/capstone-prj-architecture
        username: root
        password: root
# below are optional properties
# you may neglect, it is just for logging purpose
    jpa:
        show-sql: true
        properties:
            hibernate.format_sql: true