
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
       hibernate:
        format_sql: true