
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo
        username: root
        password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties: 
        hibernate:
            hibernate:
                ddl-auto: update
            show-sql: true
            properties:
                hibernate:
                format_sql: true
